[keyboard]
name = "RMK Keyboard"
product_name = "RMK Keyboard"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "haobo"
chip = "esp32s3"
usb_enable = false

[matrix]
# Input and output pins are mandatory
output_pins = ["gpio4", "gpio5", "gpio7", "gpio15","gpio16","gpio18"]
input_pins = ["gpio47", "gpio48", "gpio9","gpio10","gpio11"]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, row2col config here is valid ONLY when you're using cloud compilation
# row2col = true

[layout]
rows = 6
cols = 6
layers = 2
keymap = [
    [
        ["A", "B", "C","D","E","F"],
        ["Kc1", "Kc2", "Kc3","D","E","F"],
        ["A", "B", "C","D","E","F"],
        ["Kc1", "Kc2", "Kc3","D","E","F"],
        ["LCtrl", "MO(1)", "LShift","D","E","F"],
        ["OSL(1)", "LT(2, Kc9)", "LM(1, LShift | LGui)","D","E","F"]
    ],
    [
        ["A", "B", "C","D","E","F"],
        ["Kc1", "Kc2", "Kc3","D","E","F"],
        ["_", "TT(1)", "TG(2)","D","E","F"],
        ["_", "_", "_","D","E","F"],
        ["_", "_", "_","D","E","F"],
        ["_", "_", "_","D","E","F"]
    ],
]

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "PB2"
# capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true

[storage]
# Storage feature is enabled by default
# enabled = false

[ble]
enabled = true
